#!/bin/bash

USAGE="c directory"
History_File=".c_history"
target=""

function save_dir(){
  echo $1 >> ~/$History_File
}

function get_target(){
   d_name=$1
   g_name=`echo $d_name | grep "^/"` 
 
   echo "DIR: " $d_name
 
   if [ $d_name = ~ ]; then 
      echo "main directory"
      target=~ 
   elif [ $d_name = ".." -o $d_name = "." ]; then 
      echo ".. or . or absolute path "
      target=$1
   else
       echo "start to grep"
       
       dir_count=`ls -l | grep -c "$d_name"` 
       if [ $dir_count -eq 0 ]; then 
          echo  "none contains $d_name"
          echo  "input name more exactly!"
       elif [ $dir_count -eq 1 ]; then 
          target=`ls | grep "$d_name"`
       else 
         ls -l | grep "$d_name"
         echo "Need a more exact directory name!"
      fi
  fi 
}


#  script start 

if [ $# -eq 0 ]; then 
   directory="" 
elif [ $# -eq 1 ]; then 
   directory=$1
else 
   echo $USAGE 
   exit       
fi 

if [ -z $directory ]; then 
   target=~
else 
   get_target $directory 
fi 


echo "target is $target"
cd $target 
save_dir $target

