#!/bin/bash

USAGE="c directory"
History_File=".c_history"
target=""

function save_dir(){
  echo $1 >> ~/$History_File
}

function get_target(){
   part_name=$1
   echo "DIR: " $part_name
 
   if [ $1 = ~ ]; then 
      echo "main directory"
      target=~ 
   elif [ $1 = ".." -o $1 = "." -o `echo $1 | grep '^/'` ]; then 
      echo ".. or . or absolute path "
      target=$1
   else
       echo "start to grep"
       dir_name=`basename $part_name`
       dir_count=`ls -l | grep -c "$dir_name"` 
       if [ $dir_count -eq 0 ]; then 
          echo  "none contains $dir_name"
          echo  "input name more exactly!"
       elif [ $dir_count -eq 1 ]; then 
          target=`ls | grep "$dir_name"`
       else 
         ls -l | grep "$part_name"
         echo "Need a more exact directory name!"
         exit 
      fi
  fi 
}

function cx()
{
   if [ $# -eq 0 ]; then 
      directory="" 
   elif [ $# -eq 1 ]; then 
      directory=$1
   else 
      echo $USAGE 
      exit 
   fi 

   if [ -z $directory ]; then 
      target=~
   else 
      get_target $directory 
   fi 

   cd $target 
   save_dir $target
}

cx $@
